package com.example.routy.core.localization

import androidx.compose.runtime.staticCompositionLocalOf
import com.example.routy.core.transport.domain.*

enum class TextKey {
    AppName,
    City,
    Map,
    Routes,
    Stops,
    Favorites,
    Settings,
    Search,
    SearchRoutes,
    SearchStops,
    Explore,
    ExploreBody,
    AllRoutes,
    Nearby,
    Retry,
    Loading,
    Empty,
    NoResults,
    NoFavorites,
    Offline,
    Refreshing,
    NoInternet,
    Timeout,
    Server,
    Invalid,
    Storage,
    Unknown,
    Schedule,
    ScheduleNote,
    NoSchedule,
    Group,
    Unspecified,
    Save,
    Saved,
    ShowMap,
    Back,
    Close,
    Live,
    Stale,
    NoBuses,
    MyLocation,
    LocationHelp,
    LocationUnavailable,
    Language,
    Appearance,
    ColorTheme,
    Ocean,
    Violet,
    Mint,
    Mono,
    System,
    Light,
    Dark,
    English,
    Georgian,
    About,
    MapUnavailable,
    FitRoute,
    Vehicle,
    Details,
}

class Strings(
    val language: Language,
) {
    operator fun get(key: TextKey): String = (if (language == Language.Georgian) georgian else english).getValue(key)

    fun error(error: AppError): String =
        get(
            when (error) {
                AppError.NoInternet -> TextKey.NoInternet
                AppError.Timeout -> TextKey.Timeout
                AppError.ServerUnavailable -> TextKey.Server
                AppError.InvalidData -> TextKey.Invalid
                AppError.StorageUnavailable -> TextKey.Storage
                AppError.Unknown -> TextKey.Unknown
            },
        )
}

val LocalStrings = staticCompositionLocalOf { Strings(Language.English) }
private val english =
    mapOf(
        TextKey.AppName to "Routy",
        TextKey.City to "BATUMI • PUBLIC TRANSPORT",
        TextKey.Map to "Map",
        TextKey.Routes to "Routes",
        TextKey.Stops to "Stops",
        TextKey.Favorites to "Saved",
        TextKey.Settings to "Settings",
        TextKey.Search to "Find a route or stop",
        TextKey.SearchRoutes to "Route number or name",
        TextKey.SearchStops to "Stop name or number",
        TextKey.Explore to "Your city, connected",
        TextKey.ExploreBody to "Find your next ride through Batumi",
        TextKey.AllRoutes to "All routes",
        TextKey.Nearby to "Explore stops",
        TextKey.Retry to "Try again",
        TextKey.Loading to "Loading transport data…",
        TextKey.Empty to "Nothing here yet",
        TextKey.NoResults to "No matches. Try another name or number.",
        TextKey.NoFavorites to "Save routes and stops to find them here.",
        TextKey.Offline to "Saved data • updates unavailable",
        TextKey.Refreshing to "Updating transport data…",
        TextKey.NoInternet to "No connection. Check your internet and retry.",
        TextKey.Timeout to "The connection took too long. Try again.",
        TextKey.Server to "Transport service is unavailable. Try again later.",
        TextKey.Invalid to "Transport data could not be read. Try refreshing.",
        TextKey.Storage to "Changes could not be saved on this device.",
        TextKey.Unknown to "Something went wrong. Please try again.",
        TextKey.Schedule to "Scheduled departures",
        TextKey.ScheduleNote to "Batumi time • timetable, not live arrival predictions",
        TextKey.NoSchedule to "No timetable available",
        TextKey.Group to "Stop group",
        TextKey.Unspecified to "Unspecified group",
        TextKey.Save to "Save",
        TextKey.Saved to "Saved",
        TextKey.ShowMap to "Show on map",
        TextKey.Back to "Back",
        TextKey.Close to "Close",
        TextKey.Live to "Live buses",
        TextKey.Stale to "Last known positions • updates unavailable",
        TextKey.NoBuses to "No buses reported on this route",
        TextKey.MyLocation to "My location",
        TextKey.LocationHelp to "Location is optional and used only to show you on the map.",
        TextKey.LocationUnavailable to "Location unavailable. Check device permissions.",
        TextKey.Language to "Language",
        TextKey.Appearance to "Appearance",
        TextKey.ColorTheme to "Color theme",
        TextKey.Ocean to "Ocean",
        TextKey.Violet to "Violet",
        TextKey.Mint to "Mint",
        TextKey.Mono to "Mono",
        TextKey.System to "Use device setting",
        TextKey.Light to "Light",
        TextKey.Dark to "Dark",
        TextKey.English to "English",
        TextKey.Georgian to "ქართული",
        TextKey.About to "Made for everyday journeys in Batumi",
        TextKey.MapUnavailable to "Map tiles unavailable. Routes and stops remain accessible from the lists.",
        TextKey.FitRoute to "Fit route",
        TextKey.Vehicle to "Bus",
        TextKey.Details to "Details",
    )

private val georgian =
    mapOf(
        TextKey.AppName to "Routy",
        TextKey.City to "ბათუმი • საზოგადოებრივი ტრანსპორტი",
        TextKey.Map to "რუკა",
        TextKey.Routes to "მარშრუტები",
        TextKey.Stops to "გაჩერებები",
        TextKey.Favorites to "რჩეულები",
        TextKey.Settings to "პარამეტრები",
        TextKey.Search to "მოძებნეთ მარშრუტი ან გაჩერება",
        TextKey.SearchRoutes to "მარშრუტის ნომერი ან სახელი",
        TextKey.SearchStops to "გაჩერების სახელი ან ნომერი",
        TextKey.Explore to "თქვენი ქალაქი, დაკავშირებული",
        TextKey.ExploreBody to "იპოვეთ თქვენი შემდეგი მგზავრობა ბათუმში",
        TextKey.AllRoutes to "ყველა მარშრუტი",
        TextKey.Nearby to "გაჩერებების ნახვა",
        TextKey.Retry to "ხელახლა ცდა",
        TextKey.Loading to "ტრანსპორტის მონაცემები იტვირთება…",
        TextKey.Empty to "ჯერ არაფერია",
        TextKey.NoResults to "ვერაფერი მოიძებნა. სცადეთ სხვა სახელი ან ნომერი.",
        TextKey.NoFavorites to "შეინახეთ მარშრუტები და გაჩერებები, რომ აქ იპოვოთ.",
        TextKey.Offline to "შენახული მონაცემები • განახლება მიუწვდომელია",
        TextKey.Refreshing to "მონაცემები ახლდება…",
        TextKey.NoInternet to "კავშირი არ არის. შეამოწმეთ ინტერნეტი და სცადეთ ხელახლა.",
        TextKey.Timeout to "კავშირს დიდი დრო დასჭირდა. სცადეთ ხელახლა.",
        TextKey.Server to "სატრანსპორტო სერვისი მიუწვდომელია. სცადეთ მოგვიანებით.",
        TextKey.Invalid to "მონაცემები ვერ წაიკითხა. სცადეთ განახლება.",
        TextKey.Storage to "ცვლილებები მოწყობილობაზე ვერ შეინახა.",
        TextKey.Unknown to "დაფიქსირდა შეცდომა. სცადეთ ხელახლა.",
        TextKey.Schedule to "დაგეგმილი გამგზავრება",
        TextKey.ScheduleNote to "ბათუმის დრო • განრიგი, არა რეალურ დროში პროგნოზი",
        TextKey.NoSchedule to "განრიგი მიუწვდომელია",
        TextKey.Group to "გაჩერებების ჯგუფი",
        TextKey.Unspecified to "დაუზუსტებელი ჯგუფი",
        TextKey.Save to "შენახვა",
        TextKey.Saved to "შენახულია",
        TextKey.ShowMap to "რუკაზე ნახვა",
        TextKey.Back to "უკან",
        TextKey.Close to "დახურვა",
        TextKey.Live to "ავტობუსები რეალურ დროში",
        TextKey.Stale to "ბოლო ცნობილი მდებარეობები • განახლება მიუწვდომელია",
        TextKey.NoBuses to "ამ მარშრუტზე ავტობუსები არ დაფიქსირდა",
        TextKey.MyLocation to "ჩემი მდებარეობა",
        TextKey.LocationHelp to "მდებარეობა არასავალდებულოა და გამოიყენება მხოლოდ რუკაზე თქვენს საჩვენებლად.",
        TextKey.LocationUnavailable to "მდებარეობა მიუწვდომელია. შეამოწმეთ ნებართვები.",
        TextKey.Language to "ენა",
        TextKey.Appearance to "იერსახე",
        TextKey.ColorTheme to "ფერთა თემა",
        TextKey.Ocean to "Ocean",
        TextKey.Violet to "Violet",
        TextKey.Mint to "Mint",
        TextKey.Mono to "Mono",
        TextKey.System to "მოწყობილობის პარამეტრი",
        TextKey.Light to "ნათელი",
        TextKey.Dark to "მუქი",
        TextKey.English to "English",
        TextKey.Georgian to "ქართული",
        TextKey.About to "ბათუმში ყოველდღიური მგზავრობისთვის",
        TextKey.MapUnavailable to "რუკა მიუწვდომელია. მარშრუტები და გაჩერებები ხელმისაწვდომია სიებში.",
        TextKey.FitRoute to "მარშრუტის ჩვენება",
        TextKey.Vehicle to "ავტობუსი",
        TextKey.Details to "დეტალები",
    )
